spring.application.name=tunematch

spring.datasource.url=jdbc:mysql://mysqldb:3306/tunematch_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=tunematch_user
spring.datasource.password=tunematch_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.deferred-datasource-initialization=true

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=50MB

python.api.url=http://127.0.0.1:8000/analyze